# Generated by Django 4.1.4 on 2022-12-27 05:51

from django.db import migrations, models
import system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(default=system.models.generate_ref_no, max_length=13, unique=True)),
                ('business_type', models.PositiveSmallIntegerField(choices=[(1, 'Sole Proprietorship'), (2, 'One Person Corporation'), (3, 'Partnership'), (4, 'Corporation'), (5, 'Cooperative')], default=1)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'For Verification'), (2, 'Denied'), (3, 'For Assessment Of Fees'), (4, 'For Issuance'), (5, 'Issued')], default=1)),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(1, 'New Application'), (2, 'Renewal'), (3, 'Quarterly'), (4, 'Semi Annual'), (5, 'Anualy')], default=1)),
                ('transaction_date', models.DateField(auto_now=True)),
                ('owners_gender', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1)),
            ],
        ),
    ]
