# Generated by Django 4.1.4 on 2022-12-27 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='', max_length=50, unique=True)),
                ('reference_no', models.CharField(default=system.models.generate_ref_no, max_length=13, unique=True)),
                ('business_type', models.PositiveSmallIntegerField(choices=[(1, 'Sole Proprietorship'), (2, 'One Person Corporation'), (3, 'Partnership'), (4, 'Corporation'), (5, 'Cooperative')], default=1)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'For Verification'), (2, 'Denied'), (3, 'For Assessment Of Fees'), (4, 'For Issuance'), (5, 'Issued')], default=1)),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(1, 'New Application'), (2, 'Renewal'), (3, 'Quarterly'), (4, 'Semi Annual'), (5, 'Annualy')], default=1)),
                ('transaction_date', models.DateField(auto_now=True)),
                ('barangay_business_clearance', models.FileField(blank=True, upload_to='requirements/%Y/%m/%d/')),
                ('proof_of_business_name_registration', models.FileField(blank=True, upload_to='requirements/%Y/%m/%d/')),
                ('community_tax_certificate', models.FileField(blank=True, upload_to='requirements/%Y/%m/%d/', verbose_name='Community Tax Certificate(Cedula)')),
                ('business_contact_no', models.CharField(blank=True, default='', max_length=11, verbose_name='Contact No.')),
                ('business_house_no', models.CharField(blank=True, default='', max_length=40, verbose_name='House No./Bldg No.')),
                ('business_street', models.CharField(blank=True, default='', max_length=40, verbose_name='Street Name')),
                ('business_barangay', models.CharField(default='', max_length=40, verbose_name='Barangay')),
                ('tax_payer_surname', models.CharField(default='', max_length=40, verbose_name='Surname')),
                ('tax_payer_firstname', models.CharField(default='', max_length=40, verbose_name='Firstname')),
                ('tax_payer_middle_name', models.CharField(blank=True, default='', max_length=40, verbose_name='Middle Name')),
                ('tax_payer_contact_no', models.CharField(blank=True, default='', max_length=11, verbose_name='Contact No.')),
                ('tax_payer_house_no', models.CharField(blank=True, default='', max_length=40, verbose_name='House No./Bldg No.')),
                ('tax_payer_street', models.CharField(blank=True, default='', max_length=40, verbose_name='Street Name')),
                ('tax_payer_barangay', models.CharField(default='', max_length=40, verbose_name='Barangay')),
                ('tax_payer_city', models.CharField(default='', max_length=40, verbose_name='City/Municipality')),
                ('owners_gender', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
