# Generated by Django 4.1.4 on 2022-12-30 19:36

from django.db import migrations, models
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspermit',
            name='form_control_no',
            field=models.CharField(default=system.models.generate_form_control_no, max_length=26, unique=True),
        ),
    ]
