# Generated by Django 4.1.4 on 2022-12-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='owners_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
