# Generated by Django 4.1.4 on 2022-12-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='sss_no',
            field=models.CharField(blank=True, max_length=11, verbose_name='SSS. No.'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='tin_no',
            field=models.CharField(blank=True, max_length=11, verbose_name='TIN'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='treasury_name',
            field=models.CharField(default='', max_length=40, verbose_name='Name of President/Treasury of Corporation'),
        ),
    ]
