# Generated by Django 4.1.4 on 2022-12-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_businesspermit_form_control_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspermit',
            name='address',
            field=models.CharField(default='', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='businesspermit',
            name='name_of_business',
            field=models.CharField(default='', max_length=120, unique=True),
        ),
    ]
