# Generated by Django 4.1.4 on 2022-12-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_businesspermit_owners_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='fire_safety_date',
            field=models.DateField(null=True),
        ),
    ]
