# Generated by Django 4.1.4 on 2022-12-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_businesspermit_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='barangay_business_clearance',
            field=models.FileField(blank=True, upload_to='requirements/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='community_tax_certificate',
            field=models.FileField(blank=True, upload_to='requirements/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='proof_of_business_name_registration',
            field=models.FileField(blank=True, upload_to='requirements/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='businesspermit',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New Application'), (2, 'Renewal'), (3, 'Quarterly'), (4, 'Semi Annual'), (5, 'Annualy')], default=1),
        ),
    ]
