# Generated by Django 4.1.4 on 2022-12-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_businesspermit_sss_no_businesspermit_tin_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='community_tax_certificate_no',
            field=models.CharField(blank=True, max_length=30, verbose_name='Community Tax Certificate No.(Individual or Corporate)'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='community_tax_date_issued',
            field=models.DateField(auto_now=True, verbose_name='Date issued'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='community_tax_place_issued',
            field=models.CharField(blank=True, max_length=50, verbose_name='Place issued'),
        ),
        migrations.AlterField(
            model_name='businesspermit',
            name='tin_no',
            field=models.CharField(blank=True, max_length=15, verbose_name='TIN'),
        ),
    ]
