# Generated by Django 4.1.4 on 2022-12-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_businesspermit_fire_safety_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='contact_no',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='floor_area',
            field=models.CharField(default='', max_length=50),
        ),
    ]
