# Generated by Django 4.1.4 on 2023-01-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_businesspermit_business_permit_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='mayor_full_name',
            field=models.CharField(default='Mildred Joy P. Que', max_length=50),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='mayor_signature',
            field=models.ImageField(blank=True, default='signatures/signature.png', null=True, upload_to='signatures/'),
        ),
    ]
