# Generated by Django 4.1.4 on 2022-12-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_businesspermit_community_tax_certificate_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspermit',
            name='community_tax_date_issued',
            field=models.DateField(blank=True, null=True, verbose_name='Date issued'),
        ),
    ]
