# Generated by Django 4.1.4 on 2022-12-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_businesspermit_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='sketch_image',
            field=models.ImageField(blank=True, null=True, upload_to='sketches/'),
        ),
    ]
