# Generated by Django 4.1.4 on 2023-01-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_businesspermit_mayor_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mayor_full_name', models.CharField(default='Mildred Joy P. Que', max_length=50)),
                ('mayor_signature', models.ImageField(blank=True, default='signatures/signature.png', null=True, upload_to='signatures/')),
            ],
        ),
    ]
