# Generated by Django 4.1.4 on 2022-12-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_businesspermit_contact_no_businesspermit_floor_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='address',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='certified_by',
            field=models.CharField(default='', max_length=50),
        ),
    ]
