# Generated by Django 4.1.4 on 2022-12-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_businesspermit_community_tax_date_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='transfer_of_ownership_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='If transfer of ownership from whom acquired'),
        ),
    ]
