# Generated by Django 4.1.4 on 2023-01-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_businesspermit_sketch_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='deny_reason',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='deny_remarks',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
