# Generated by Django 4.1.4 on 2022-12-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_businesspermit_transfer_of_ownership_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='pagibig_no',
            field=models.CharField(blank=True, max_length=12, verbose_name='Pag-ibig No.'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='philhealth_no',
            field=models.CharField(blank=True, max_length=14, verbose_name='Philhealth No.'),
        ),
    ]
