# Generated by Django 4.1.4 on 2022-12-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_businesspermit_address_businesspermit_certified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='customer_relation_officer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='fire_inspection_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='time_date_received',
            field=models.DateField(null=True),
        ),
    ]
