# Generated by Django 4.1.4 on 2022-12-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_businesspermit_customer_relation_officer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='area_used',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='no_of_employees',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
