# Generated by Django 4.1.4 on 2022-12-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_businesspermit_email_businesspermit_pagibig_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='delivery_trucks_no',
            field=models.PositiveIntegerField(default=0, verbose_name='Delivery Trucks/Vehicles No. of Units'),
        ),
    ]
