# Generated by Django 4.1.4 on 2022-12-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_businesspermit_delivery_trucks_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='employee_no_male',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
