# Generated by Django 4.1.4 on 2022-12-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_businesspermit_area_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='double_faced',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='no_of_chairs',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='no_of_tables',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='single_faced',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
