# Generated by Django 4.1.4 on 2022-12-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_businesspermit_double_faced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='seating_capacity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='space_lot_rental',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
