# Generated by Django 4.1.4 on 2022-12-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_businesspermit_employee_no_male'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='employee_no_female',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
