# Generated by Django 4.1.4 on 2022-12-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_businesspermit_employee_no_female'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='employee_no_female_residing',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='employee_no_male_residing',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
