# Generated by Django 4.1.4 on 2022-12-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_businesspermit_estimated_capitalization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='motorized_delivery',
            field=models.CharField(blank=True, default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='motorized_peddling',
            field=models.CharField(blank=True, default='0', max_length=30),
        ),
    ]
