# Generated by Django 4.1.4 on 2022-12-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_businesspermit_employee_no_female_residing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='code_1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='code_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='code_3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='code_4',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
