# Generated by Django 4.1.4 on 2022-12-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_businesspermit_motorized_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='others_delivery',
            field=models.CharField(blank=True, default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='others_peddling',
            field=models.CharField(blank=True, default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='pedicabs_delivery',
            field=models.CharField(blank=True, default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='pedicabs_peddling',
            field=models.CharField(blank=True, default='0', max_length=30),
        ),
    ]
