# Generated by Django 4.1.4 on 2022-12-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_businesspermit_code_1_businesspermit_code_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='line_of_business_1',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='line_of_business_2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='line_of_business_3',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='line_of_business_4',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
