# Generated by Django 4.1.4 on 2022-12-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_businesspermit_line_of_business_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='receipts_1',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='receipts_2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='receipts_3',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='receipts_4',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
