# Generated by Django 4.1.4 on 2022-12-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_businesspermit_others_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='bplo_inspector',
            field=models.CharField(default='', max_length=50),
        ),
    ]
