# Generated by Django 4.1.4 on 2022-12-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_businesspermit_bplo_inspector'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='inspection_date',
            field=models.DateField(auto_now=True),
        ),
    ]
