# Generated by Django 4.1.4 on 2022-12-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_businesspermit_receipts_1_businesspermit_receipts_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='paid_up_1',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='paid_up_2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='paid_up_3',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='paid_up_4',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='subscribed_1',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='subscribed_2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='subscribed_3',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='subscribed_4',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
