# Generated by Django 4.1.4 on 2022-12-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_businesspermit_paid_up_1_businesspermit_paid_up_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='estimated_area',
            field=models.CharField(blank=True, max_length=20, verbose_name='Estimated area used in business'),
        ),
    ]
