# Generated by Django 4.1.4 on 2022-12-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_businesspermit_estimated_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspermit',
            name='delivery_trucks_no',
            field=models.PositiveIntegerField(verbose_name='Delivery Trucks/Vehicles No. of Units'),
        ),
    ]
