# Generated by Django 4.1.4 on 2022-12-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_businesspermit_activities_main1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='others_no_of_units1',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='others_no_of_units2',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='others_no_of_units3',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='others_no_of_units4',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='others_taxable_items1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='others_taxable_items2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='others_taxable_items3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='others_taxable_items4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
