# Generated by Django 4.1.4 on 2022-12-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_alter_businesspermit_delivery_trucks_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='owners_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
