# Generated by Django 4.1.4 on 2022-12-28 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_businesspermit_owners_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesspermit',
            old_name='owners_name',
            new_name='owner_name',
        ),
    ]
