# Generated by Django 4.1.4 on 2022-12-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_rename_owners_name_businesspermit_owner_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesspermit',
            old_name='owner_name',
            new_name='owner_rented_name',
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='owner_rented_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
