# Generated by Django 4.1.4 on 2022-12-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_rename_owner_name_businesspermit_owner_rented_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='administrator_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Administrator (If name of owner is not available)'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='rent_per_month',
            field=models.PositiveIntegerField(null=True, verbose_name='Rent per month'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='rent_start',
            field=models.DateField(null=True, verbose_name='Rent start(monthly/year)'),
        ),
    ]
