# Generated by Django 4.1.4 on 2022-12-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_businesspermit_administrator_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspermit',
            name='delivery_trucks_no',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Delivery Trucks/Vehicles No. of Units'),
        ),
        migrations.AlterField(
            model_name='businesspermit',
            name='employee_no_female',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='businesspermit',
            name='employee_no_female_residing',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='businesspermit',
            name='employee_no_male',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='businesspermit',
            name='employee_no_male_residing',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='businesspermit',
            name='rent_per_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rent per month'),
        ),
    ]
