# Generated by Django 4.1.4 on 2022-12-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_alter_businesspermit_delivery_trucks_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspermit',
            name='business_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sole Proprietorship'), (2, 'One Person Corporation'), (3, 'Partnership'), (4, 'Corporation'), (5, "People's Organization")], default=1),
        ),
    ]
