# Generated by Django 4.1.4 on 2022-12-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_alter_businesspermit_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='boi_date_issued',
            field=models.DateField(null=True, verbose_name='Date issued'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='boi_no',
            field=models.CharField(blank=True, max_length=30, verbose_name='BOI no.'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='cda_date_issued',
            field=models.DateField(null=True, verbose_name='Date issued'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='cda_no',
            field=models.CharField(blank=True, max_length=30, verbose_name='DTI no.'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='certificate_of_occupancy_date_issued',
            field=models.DateField(null=True, verbose_name='Date issued'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='certificate_of_occupancy_no',
            field=models.CharField(blank=True, max_length=30, verbose_name='Certificate of occupancy no.'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='dole_date_issued',
            field=models.DateField(null=True, verbose_name='Date issued'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='dole_reg_no',
            field=models.CharField(blank=True, max_length=30, verbose_name='DOLE reg no.'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='dti_date_issued',
            field=models.DateField(null=True, verbose_name='Date issued'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='dti_no',
            field=models.CharField(blank=True, max_length=30, verbose_name='DTI no.'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='location_clearance_date_issued',
            field=models.DateField(null=True, verbose_name='Date issued'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='location_clearance_no',
            field=models.CharField(blank=True, max_length=30, verbose_name='Location clearance no.'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='sec_reg_date_issued',
            field=models.DateField(null=True, verbose_name='Date issued'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='sec_reg_no',
            field=models.CharField(blank=True, max_length=30, verbose_name='SEC reg no.'),
        ),
    ]
