# Generated by Django 4.1.4 on 2022-12-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_alter_businesspermit_boi_date_issued_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspermit',
            name='certificate_of_occupancy_date_issued',
            field=models.DateField(blank=True, null=True, verbose_name='Date issued'),
        ),
    ]
