# Generated by Django 4.1.4 on 2022-12-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0025_alter_businesspermit_certificate_of_occupancy_date_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='barangay_business_clearance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='fire_safety_inspection_clearance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='health_clearance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='location_zoning_clearance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='occupancy_permit_clearance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='others_clearance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='police_clearance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
