# Generated by Django 4.1.4 on 2022-12-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_businesspermit_barangay_business_clearance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='barangay_business_clearance_verified_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='fire_safety_inspection_clearance_verified_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='health_clearance_verified_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='location_zoning_clearance_verified_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='occupancy_permit_clearance_verified_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='others_clearance',
            field=models.CharField(blank=True, max_length=30, verbose_name='Others, please sepecify'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='others_clearance_verified_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='police_clearance_verified_by',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
